### ISSUE TITLE
Homomorphic operations

### ISSUE THREAD

**Issue by SayyedF** [rs3vans/krypto#3]
Hi Ryan,

Sorry to ask here!
Which of the following operations are supported by krypto???

- 1. Addition/Subtraction
- 2. Multiplication
- 3. Division
- 4. Mode
- 5. Min/Max
- 6. Range Count
- 7. Comparison (using bit operations?)
- 8. Equality

I want to use krypto for masters project

**Comment by rs3vans** [comment]
Hi! Thanks for your interest in this project. I'm afraid I've done nothing special to add any of these features to this project. This project's intention was to make using the standard JDK encryption classes easier, and to enforce more secure choices.

I'd be glad to look into adding features like this as I have time, though.

**Comment by SayyedF** [comment]
Okay.
Thanks for prompt reply!!
